config/routes.rb
Rails.application.routes.draw do
  get '/rooms/:id' => 'rooms#show'
  root 'pages#index'
  get 'pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
      ActionCable.server.broadcast('notification_channel', 'You have visited the welcome page.')
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room_id = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcExplorer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>index.html.erb</p>
<p> This page is showing on localhost:3000</p>

<%= link_to 'Send Notification', pages_index_path, remote: true %>
The above line is for Send Push Notification


<div id="room-id" data-room-id="<%= @room_id %>"> </div>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>show.html.erb</p>
<p> This page is showing result for manually selected page</p>

<div id="room-id" data-room-id="<%= @room_id %>"> </div>